# Generated by Django 5.2.6 on 2025-10-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('archivo', models.URLField(blank=True, max_length=500, null=True)),
                ('cloudinary_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Canciones',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.cancion')),
            ],
            options={
                'verbose_name_plural': 'Historial',
                'ordering': ['-fecha_reproduccion'],
            },
        ),
    ]
